### PR TITLE
Task 7: vote on an article

### PR DESCRIPTION
**Pull request by ak5cel**
Added a VoteAdder with an UpvoteButton and a DownVoteButton (all to be reused later when upvoting/downvoting comments)

I've done the requirements in the ticket, but there's a couple of issues I'm not sure when we're expected to fix:
1. Users can currently do as many upvotes and downvotes as they like
2. Any user can like any user's article, including their own

Do let me know if I should do any of them for this PR (by hardcoding a logged in user for the time-being as there's no authentication), or if we should do them once the core tasks are done 🎯

### CODE REVIEW

**Comment by nc-saleh** [comment]
Some great code! A few comments: 

 - currently a user can vote as many times as possible - they should only be able to do so once!
 
 please amend this and then I resubmit a new pr

**Comment by ak5cel** [comment]
Thanks! I've modified the upvote/downvote buttons to only allow one per article. They function as below:
1. Initially, both are enabled: 
    buttons-1
2. Clicking upvote disables downvote:
    buttons-2
3. Clicking it again will undo the upvote and enable both again
    buttons-3

(downvote button works similarly)

Resubmitting, do let me know if that works for this PR or if I should make any changes 👍

**Review by nc-nick-jones — CHANGES_REQUESTED** [review]
This is really good! But we need some user feedback for when the patch/vote fails ! 
Please add this in when ready !

**Comment by ak5cel** [comment]
Added a Snackbar pop up when it encounters an error (did it by using notistack so I could reuse it for errors in the next few tasks)

It looks like this for a network error:

snackbar-error

For other errors, it's a 'Oops. something went wrong' msg for now 😅

**Pull request merged**
